// Auto-generated by scripts/generate-types.mjs
// Do not edit manually - regenerate with: npm run generate-types

import type { Entry, Asset, EntryFieldTypes, EntrySkeletonType } from 'contentful';

// Resolved asset type
export interface ContentfulAsset {
  url: string;
  title: string;
  description?: string;
  width?: number;
  height?: number;
  contentType?: string;
}

// Contentful Entry Skeleton Types

export interface GlobalSkeleton {
  contentTypeId: 'global';
  fields: {
    name: EntryFieldTypes.Text;
    header?: EntryFieldTypes.EntryLink<HeaderSkeleton>;
  };
}

export interface HeaderSkeleton {
  contentTypeId: 'header';
  fields: {
    name: EntryFieldTypes.Text;
    logo?: EntryFieldTypes.AssetLink;
    navItems?: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<NavLinkSkeleton | NavGroupSkeleton>>;
    loginText?: EntryFieldTypes.Text;
    loginUrl?: EntryFieldTypes.Text;
  };
}

export interface NavGroupSkeleton {
  contentTypeId: 'navGroup';
  fields: {
    label: EntryFieldTypes.Text;
    links: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<NavLinkSkeleton>>;
  };
}

export interface NavLinkSkeleton {
  contentTypeId: 'navLink';
  fields: {
    label: EntryFieldTypes.Text;
    url: EntryFieldTypes.Text;
  };
}

export interface LandinPageSkeleton {
  contentTypeId: 'landinPage';
  fields: {
    entryId: EntryFieldTypes.Text;
    title: EntryFieldTypes.Text;
  };
}

// Resolved Entry Types (what you get after fetching and parsing)

export interface Global {
  name: string;
  header?: Header;
}

export interface Header {
  name: string;
  logo?: ContentfulAsset;
  navItems?: (NavLink | NavGroup)[];
  loginText?: string;
  loginUrl?: string;
}

export interface NavGroup {
  label: string;
  links: (NavLink)[];
}

export interface NavLink {
  label: string;
  url: string;
}

export interface LandinPage {
  entryId: string;
  title: string;
}

